from datetime import datetime

from swmtplanner.swmttypes.product import Greige
from swmtplanner.swmttypes.demand import Order, Safety

__all__ = ['InvTracker']

class InvTracker:
    def __init__(self, item: Greige, safety_lbs: float, safety_rolls: int,
                 init_lbs: float, init_rolls: int) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def safety_lbs(self) -> float: ...
    @property
    def safety_rolls(self) -> int: ...
    def create_order(self, date: datetime, rolls: int) -> Order: ...
    def create_safety(self, week: int) -> Safety: ...
    def net_position_by(self, date: datetime) -> float: ...