from typing import Any

from ...sqlload.table import Row

__all__ = ['PageModel']


class PageModel:
    def __init__(self, columns: list[str], rows: list[Row] | None = ...) -> None: ...
    def rowCount(self, parent: Any = ...) -> int: ...
    def columnCount(self, parent: Any = ...) -> int: ...
    def data(self, index: Any, role: int = ...) -> Any: ...
    def headerData(self, section: int, orientation: Any, role: int = ...) -> Any: ...
    def set_rows(self, rows: list[Row]) -> None: ...
    def reset(self, columns: list[str], rows: list[Row]) -> None: ...
