from typing import Any

from ...sqlload.table import Row

__all__ = ['PageModel']


class PageModel:
    def __init__(
        self, columns: list[str], rows: list[Row] | None = ...,
        has_checkbox: bool = ..., fk_cols: set[str] | None = ...,
    ) -> None: ...
    def rowCount(self, parent: Any = ...) -> int: ...
    def columnCount(self, parent: Any = ...) -> int: ...
    def row_at(self, row_idx: int) -> Row: ...
    def set_hover(self, row: int, col: int) -> None: ...
    def data(self, index: Any, role: int = ...) -> Any: ...
    def flags(self, index: Any) -> Any: ...
    def setData(self, index: Any, value: Any, role: int = ...) -> bool: ...
    def headerData(self, section: int, orientation: Any, role: int = ...) -> Any: ...
    def set_rows(self, rows: list[Row]) -> None: ...
    def reset(
        self, columns: list[str], rows: list[Row],
        has_checkbox: bool = ..., fk_cols: set[str] | None = ...,
    ) -> None: ...
