from swmtplanner.support import HasID, WorkCal
from swmtplanner.swmttypes.product import Greige, BeamSet
from swmtplanner.swmttypes.schedule import Job

class Machine(HasID[str]):
    def __init__(self, name: str, cal: WorkCal, item: Greige, top_rem: float,
                 btm_rem: float, ): ...
    @property
    def cal(self) -> WorkCal: ...
    @property
    def item(self) -> Greige: ...
    @property
    def top_set(self) -> BeamSet: ...
    @property
    def btm_set(self) -> BeamSet: ...