from swmtplanner.support import SwmtBase, HasID

__all__ = ['BeamSet']

class BeamSet(SwmtBase, HasID[str],
              read_only=('id','denier','kind','ends','beams','split')):
    def __init__(self, desc: str) -> None: ...
    @property
    def denier(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def ends(self) -> int: ...
    @property
    def beams(self) -> int: ...
    @property
    def split(self) -> bool: ...