from typing import NamedTuple, Generator
from enum import Enum
from io import TextIOBase
from swmtplanner.excel.interpreter.file import FilePos

class TokType(Enum):
    START = ...
    END = ...
    NEWLINE = ...
    WS = ...
    INDENT = ...
    EQUALS = ...
    COLON = ...
    COMMA = ...
    ELLIPSIS = ...
    NAME = ...
    FILE = ...
    NUMBER = ...
    STRING = ...
    COMMENT = ...

class Token(NamedTuple):
    kind: TokType
    value: str
    start: FilePos

class Lexer:
    """Represents a tokenizing engine for excel info files."""
    def __init__(self, buffer: TextIOBase) -> None:
        """Initialize a new Lexer from a file buffer."""
        ...
    def __iter__(self) -> Generator[Token]:
        """Generate the syntactically-relevant tokens from the underlying stream."""
        ...
    def backup(self, n: int) -> None:
        """Back up the stream by n tokens."""
        ...

def tokenize(buffer: TextIOBase) -> Generator[Token]:
    """Generate tokens from a file buffer."""
    ...