from . import schedule

import datetime as dt
from swmtplanner.support import SwmtBase, HasID, DateRange, FloatRange
from swmtplanner.planners.parkave.materials import DyeLot
from swmtplanner.planners.parkave.jet.schedule import DyeCycle, DyeCycleView, JetSched

__all__ = ['schedule', 'Jet']

class Jet(SwmtBase, HasID[str],
          read_only=('prefix','id','n_ports','load_rng',
                     'date_rng','days_open'),
          priv=('sched',)):
    def __init__(self, id: str, n_ports: int, load_rng: FloatRange,
                 date_rng: DateRange, days_open: FloatRange = ...) -> None: ...
    @property
    def n_ports(self) -> int: ...
    @property
    def load_rng(self) -> FloatRange: ...
    @property
    def date_rng(self) -> DateRange: ...
    @property
    def days_open(self) -> FloatRange: ...
    @property
    def jobs(self) -> list[DyeCycleView]: ...
    @property
    def prod_jobs(self) -> list[DyeCycleView]: ...
    def get_start_idx(self, due_date: dt.datetime) -> int: ...
    def try_insert(self, lots: list[DyeLot], idx: int) \
        -> tuple[JetSched | None, list[DyeCycle], list[DyeCycleView]]: ...
    def set_sched(self, newsched: JetSched) -> JetSched: ...