from typing import NamedTuple, Generator
from enum import Enum
from swmtplanner.excel.parser.file import FilePos, CharStream

class TokType(Enum):
    START = ...
    INDENT = ...
    WS = ...
    NEWLINE = ...
    STRING = ...
    NUM = ...
    NAME = ...
    FILE = ...
    COLON = ...
    EQUALS = ...
    COMMA = ...
    ELLIPSIS = ...
    COMMENT = ...

class Token(NamedTuple):
    kind: TokType
    value: str
    start: FilePos

def get_toks(f: CharStream) -> Generator[Token]: ...