from typing import NamedTuple, Iterator
from enum import Enum
from io import TextIOBase
from swmtplanner.excel.parser.file import FilePos

__all__ = ['TokType', 'Token', 'TokStream']

class TokType(Enum):
    START = ...
    END = ...
    INDENT = ...
    WS = ...
    NEWLINE = ...
    STRING = ...
    NUM = ...
    NAME = ...
    FILE = ...
    COLON = ...
    EQUALS = ...
    COMMA = ...
    ELLIPSIS = ...
    COMMENT = ...

class Token(NamedTuple):
    kind: TokType
    value: str
    start: FilePos

class TokStream(Iterator[Token]):
    def __init__(self, buffer: TextIOBase) -> None: ...
    def __iter__(self) -> Iterator[Token]: ...
    def __next__(self) -> Token: ...
    def backup(self, n: int = 1) -> None: ...