from typing import NamedTuple, Generator
from enum import Enum
from swmtplanner.excel.engine import file

__all__ = ['TokType', 'Token', 'tokenize']

def tokenize(f: file.File) -> Generator[Token]: ...

class TokType(Enum):
    LBRACK = ...
    RBRACK = ...
    LPAREN = ...
    RPAREN = ...
    COLON = ...
    COMMA = ...
    EQ = ...
    DOT = ...
    PLUS = ...
    MINUS = ...
    STAR = ...
    SLASH = ...
    MOD = ...
    ARROW = ...
    ELLIPSIS = ...
    USE = ...
    FROM = ...
    TO = ...
    NAME = ...
    REF = ...
    INT = ...
    FLOAT = ...
    STRING = ...
    COMMENT = ...
    NEWLINE = ...
    WS = ...
    RAW_INDENT = ...
    INDENT = ...
    DEDENT = ...
    END = ...

class Token(NamedTuple):
    kind: TokType
    value: str
    start: file.Pos