__all__ = ['Counters']

class Counters:
    def __init__(self, names: list[str] = ...) -> None: ...
    def __call__(self, ctr_name: str) -> int: ...
    @property
    def ctr_names(self) -> tuple[str, ...]: ...
    def advance(self, ctr_name: str) -> int: ...
    def add_counter(self, ctr_name: str) -> None: ...