from typing import Any, Callable

__all__ = ['MembershipBody', 'RangeBody', 'PatternBody']


class MembershipBody:
    def __init__(self, parent: Any = ...) -> None: ...
    def load(self, getter: Callable[[], list | None]) -> None: ...
    def selected_values(self) -> set: ...
    def is_valid(self) -> bool: ...


class RangeBody:
    def __init__(self, col_type: str, parent: Any = ...) -> None: ...
    def bounds(self) -> tuple: ...
    def is_valid(self) -> bool: ...


class PatternBody:
    def __init__(self, parent: Any = ...) -> None: ...
    def text(self) -> str: ...
    def is_valid(self) -> bool: ...
