from typing import Any

__all__ = ['FilterHeader']


class FilterHeader:
    def __init__(self, parent: Any = ...) -> None: ...
    def set_filtered(self, col: int, on: bool) -> None: ...
    def set_skip_leading(self, n: int) -> None: ...
