from swmtplanner.support import HasID

__all__ = ['BeamSet']

class BeamSet(HasID[str]):
    def __init__(self, id: str) -> None: ...
    @property
    def denier(self) -> int: ...
    @property
    def ends(self) -> int: ...
    @property
    def spools(self) -> int: ...
    @property
    def split_lease(self) -> bool: ...
    @property
    def yarn_desc(self) -> str: ...