from typing import Protocol, Hashable
from abc import abstractmethod

__all__ = ['HasID']

class HasID[T: Hashable](Protocol):
    def __eq__(self, value: 'HasID') -> bool: ...
    def __hash__(self) -> int: ...
    @property
    def prefix(self) -> str: ...
    @property
    @abstractmethod
    def id(self) -> T: ...