import datetime as dt
from swmtplanner.support import SwmtBase, Viewer, Quantity
from swmtplanner.swmttypes.products import GreigeStyle, fabric, FabricItem
from swmtplanner.swmttypes.materials import Status, Lot, LotView
from swmtplanner.planners.parkave.materials import PortLoad

__all__ = ['DyeLot', 'DyeLotView']

class DyeLot(SwmtBase, Lot[str, GreigeStyle, FabricItem],
             read_only=('id','rawmat','product','ports','status','received',
                        'cycle_time','fin_time'),
             priv=('start','view')):
    def __init__(self, id: str, rawmat: GreigeStyle, product: FabricItem,
                 ports: list[PortLoad], status: Status, received: dt.datetime,
                 start: dt.datetime | None, cycle_time: dt.timedelta,
                 fin_time: dt.timedelta) -> None: ...
    @property
    def prefix(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def color(self) -> fabric.Color: ...
    @property
    def shade(self) -> fabric.color.Shade: ...
    @property
    def ports(self) -> tuple[PortLoad, ...]: ...
    @property
    def qty(self) -> Quantity: ...
    @property
    def cycle_time(self) -> dt.timedelta: ...
    @property
    def fin_time(self) -> dt.timedelta: ...
    @property
    def start(self) -> dt.datetime | None: ...
    @start.setter
    def start(self, new: dt.datetime | None) -> None: ...
    @property
    def fin(self) -> dt.datetime | None: ...
    def view(self) -> DyeLotView: ...

class DyeLotView(Viewer[DyeLot], LotView[str, GreigeStyle, FabricItem],
                 dunders=('hash','eq','repr'),
                 attrs=('prefix','id','rawmat','product','color','shade',
                        'ports','status','received','cycle_time','fin_time',
                        'start','fin')):
    @property
    def prefix(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def color(self) -> fabric.Color: ...
    @property
    def shade(self) -> fabric.color.Shade: ...
    @property
    def ports(self) -> tuple[PortLoad, ...]: ...
    @property
    def qty(self) -> Quantity: ...
    @property
    def cycle_time(self) -> dt.timedelta: ...
    @property
    def fin_time(self) -> dt.timedelta: ...
    @property
    def start(self) -> dt.datetime | None: ...
    @property
    def fin(self) -> dt.datetime | None: ...