from .holidays import *
from datetime import date, datetime

__all__ = ['FlexDate', 'FixedDate', 'load_holidays', 'WorkCal']

class WorkCal:
    def __init__(self, work_days: list[int], day_start: int, day_end: int,
                 holidays: list[FlexDate | FixedDate], cal_shift: int = 0): ...
    @property
    def work_days(self) -> tuple[int, ...]: ...
    @property
    def days_per_week(self) -> int: ...
    @property
    def work_hours(self) -> tuple[int, int]: ...
    @property
    def hours_per_day(self) -> int: ...
    @property
    def holidays(self) -> tuple[FlexDate | FixedDate]: ...
    def is_holiday(self, d: date) -> bool: ...
    def is_workday(self, d: date) -> bool: ...
    def snap_to_work_date(self, d: date, direction: int = 1) -> date:
        """Snap d to the nearest work date in the direction provided."""
        ...
    def offset_work_days(self, start: date, days: int) -> date:
        """Offset from start by the provided number of days. When days=0 and start
        is not a work day, it will snap forward to the next one."""
        ...
    def offset_work_hours(self, start: datetime, hours: float) -> datetime:
        """Offset from start by the provided amount of hours. Same snapping behavior
        as offset_work_days."""
        ...
    def get_work_hours_between(self, start: datetime, end: datetime) -> float:
        """Get the available work hours between the two datetimes, skipping
        weekends and holidays."""
        ...