from typing import Callable, Protocol, TypeVar

__all__ = ['Queue']

CT = TypeVar('CT')

class _Comparable(Protocol):
    def __lt__(self: CT, other: CT) -> bool: ...

class Queue[T, U: _Comparable]:
    def __init__(self, key_func: Callable[[T], U]) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def put(self, item: T) -> None: ...
    def get(self) -> T: ...
    def peek(self) -> T: ...