from datetime import date, datetime
from typing import Any

from .manifest import Column

__all__ = [
    'quote', 'stem', 'physical_columns', 'to_storage', 'from_storage',
    'sort_expr', 'encode_date', 'decode_date', 'encode_time', 'decode_time',
    'encode_datetime', 'decode_datetime',
]


def quote(ident: str) -> str: ...
def stem(name: str) -> str: ...
def physical_columns(col: Column) -> tuple[str, ...]: ...
def encode_date(d: Any) -> int: ...
def decode_date(n: int) -> date: ...
def encode_time(t: Any) -> int: ...
def decode_time(n: int) -> tuple[int, int, int]: ...
def encode_datetime(dt: Any) -> int: ...
def decode_datetime(n: int) -> datetime: ...
def to_storage(col: Column, value: Any) -> tuple: ...
def from_storage(col: Column, *cells: Any) -> Any: ...
def sort_expr(col: Column, table: str) -> str: ...
