from datetime import datetime

from swmtplanner.support import HasID
from swmtplanner.swmttypes.product import Greige
from swmtplanner.swmttypes.demand import Req
from swmtplanner.swmttypes.schedule import Stop

__all__ = ['Job']

class Job(HasID[str]):
    def __init__(self, item: Greige, start: datetime, end: datetime,
                 lbs_used_top: float, lbs_used_btm: float, lbs_prod: float,
                 stops: list[Stop], req: Req | None = ...) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def req(self) -> Req | None: ...
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def lbs_used_top(self) -> float: ...
    @property
    def lbs_used_btm(self) -> float: ...
    @property
    def lbs_prod(self) -> float: ...
    @property
    def stops(self) -> tuple[Stop, ...]: ...