from typing import Any

from ..manifest import TableSpec
from .helpers import FilterKind

__all__ = ['Table', 'Row']


class Row:
    def __init__(self, table: Table, data: tuple) -> None: ...
    @property
    def data(self) -> tuple: ...
    @property
    def pk_col(self) -> str | None: ...
    @property
    def selected(self) -> bool: ...
    def get(self, column: str) -> Any: ...
    def select(self) -> None: ...
    def deselect(self) -> None: ...


class Table:
    @classmethod
    def set_page_size(cls, n: int) -> None: ...
    @property
    def page_size(self) -> int: ...
    def __init__(self, schema: TableSpec, cursor: Any, run_id: int) -> None: ...
    @property
    def schema(self) -> TableSpec: ...
    @property
    def nrows(self) -> int: ...
    @property
    def selected_keys(self) -> set: ...
    @property
    def displayed_range(self) -> tuple[int, int]: ...
    def next_page(self) -> list[Row]: ...
    def prev_page(self) -> list[Row]: ...
    def reload_page(self) -> list[Row]: ...
    def apply_filter_to(self, col: str, kind: FilterKind, rule: Any) -> None: ...
    def remove_filter(self, col: str) -> None: ...
    def apply_fk_lookup(self, fkcol: str, values: set) -> None: ...
