__all__ = ['LinkedList']

class LinkedList:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    @property
    def prev(self) -> LinkedList | None: ...
    @property
    def nxt(self) -> LinkedList | None: ...
    def append(self, node: LinkedList) -> None: ...
    def get(self, i: int) -> LinkedList: ...