from swmtplanner.support import SwmtBase, HasID
from swmtplanner.swmttypes.product import BeamSet
from swmtplanner.swmttypes.materials.inventory import Snapshot, Alloc

class Set(SwmtBase, HasID[str],
          read_only=('id','beamset'),
          priv=('init_lbs','allocs','temp_allocs','snapshot')):
    def __init__(self, bid: str, bset: BeamSet, lbs: float) -> None: ...
    @property
    def snapshot(self) -> Snapshot | None: ...
    @snapshot.setter
    def snapshot(self, new: Snapshot | None) -> None: ...
    @property
    def lbs(self) -> float: ...
    def allocate(self, lbs: float, snapshot: Snapshot | None = ...) -> Alloc: ...
    def deallocate(self, piece: Alloc, snapshot: Snapshot | None = ...) -> None: ...
    def apply_snap(self, snapshot: Snapshot | None = ...) -> None: ...