from .roll import *

from typing import Generator, overload
from swmtplanner.support.grouped import Atom, AtomView, Grouped, GroupedView
from swmtplanner.swmttypes.products import GreigeStyle
from swmtplanner.swmttypes.materials import Status

__all__ = ['KnitPlant', 'GrgRollSize', 'GRollAlloc', 'PortLoad', 'GrgRoll',
           'GrgRollView', 'PAInv']

class _RollAtom(Atom[str]):
    def __getitem__(self, key: tuple[()]) -> _RollAtomView: ...
    @property
    def data(self) -> GrgRollView | None: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _RollAtomView: ...

class _RollAtomView(AtomView[str]):
    def __getitem__(self, key: tuple[()]) -> _RollAtomView: ...
    @property
    def data(self) -> GrgRollView | None: ...
    def get(self, id: str) -> GrgRollView: ...
    def itervalues(self) -> Generator[GrgRollView]: ...

class _SizeGroup(Grouped[str, str]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: str | tuple[str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def iterkeys(self) -> Generator[tuple[str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _SizeGroupView: ...

class _SizeGroupView(GroupedView[str, str]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: str | tuple[str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def iterkeys(self) -> Generator[tuple[str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...

class _ItemGroup(Grouped[str, GrgRollSize]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: GrgRollSize | tuple[GrgRollSize]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GrgRollSize, str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def iterkeys(self) -> Generator[tuple[GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _ItemGroupView: ...

class _ItemGroupView(GroupedView[str, GrgRollSize]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: GrgRollSize | tuple[GrgRollSize]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GrgRollSize, str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def iterkeys(self) -> Generator[tuple[GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...

class _PlantGroup(Grouped[str, GreigeStyle]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: GreigeStyle | tuple[GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GreigeStyle, GrgRollSize]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GreigeStyle, GrgRollSize, str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def iterkeys(self) -> Generator[tuple[GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _PlantGroupView: ...

class _PlantGroupView(GroupedView[str, GrgRollSize]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: GreigeStyle | tuple[GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GreigeStyle, GrgRollSize]) -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[GreigeStyle, GrgRollSize, str]) -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def iterkeys(self) -> Generator[tuple[GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...

class _StatusGroup(Grouped[str, KnitPlant]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _StatusGroupView: ...
    @overload
    def __getitem__(self, key: KnitPlant | tuple[KnitPlant]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle, GrgRollSize]) \
        -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle, GrgRollSize, str]) \
        -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def iterkeys(self) -> Generator[tuple[KnitPlant, GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _StatusGroupView: ...

class _StatusGroupView(GroupedView[str, KnitPlant]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _StatusGroupView: ...
    @overload
    def __getitem__(self, key: KnitPlant | tuple[KnitPlant]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle, GrgRollSize]) \
        -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[KnitPlant, GreigeStyle, GrgRollSize, str]) \
        -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def iterkeys(self) -> Generator[tuple[KnitPlant, GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...

class PAInv(Grouped[str, Status]):
    def __init__(self) -> None:
        """Initialize a new Park Ave raw materials inventory."""
        ...
    @overload
    def __getitem__(self, key: tuple[()]) -> _PAInvView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle, GrgRollSize]) \
        -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle, GrgRollSize, str]) \
        -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def add(self, data: GrgRoll) -> None: ...
    def remove(self, dview: GrgRollView, remkey: bool = False) -> GrgRoll: ...
    def iterkeys(self) -> Generator[tuple[Status, KnitPlant, GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...
    def view(self) -> _PAInvView: ...

class _PAInvView(GroupedView[str, Status]):
    @overload
    def __getitem__(self, key: tuple[()]) -> _PAInvView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant]) -> _PlantGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle]) -> _ItemGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle, GrgRollSize]) \
        -> _SizeGroupView: ...
    @overload
    def __getitem__(self, key: tuple[Status, KnitPlant, GreigeStyle, GrgRollSize, str]) \
        -> _RollAtomView: ...
    def get(self, id: str) -> GrgRollView: ...
    def iterkeys(self) -> Generator[tuple[Status, KnitPlant, GreigeStyle, GrgRollSize, str]]: ...
    def itervalues(self) -> Generator[GrgRollView]: ...