from swmtplanner.support import SwmtBase, HasID
from swmtplanner.swmttypes.product import BeamSet

STYLES: dict[str, Greige] = ...

def load_styles(fpath: str) -> None: ...

class Greige(SwmtBase, HasID[str],
             read_only=('id','family','roll_avg','rate','gauge','top_set',
                        'top_pct','btm_set','btm_pct'),
             priv=('machines',)):
    def __init__(self, style: str, roll_avg: float, family: str = ..., rate: float = ...,
                 gauge: int = ..., top_set: str | None = ..., top_pct: float = ...,
                 btm_set: str | None = ..., btm_pct: float = ...,
                 machines: list[str] = ...) -> None: ...
    @property
    def family(self) -> str: ...
    @property
    def rate(self) -> float: ...
    @property
    def gauge(self) -> int: ...
    @property
    def top_set(self) -> BeamSet | None: ...
    @property
    def top_pct(self) -> float: ...
    @property
    def btm_set(self) -> BeamSet | None: ...
    @property
    def btm_pct(self) -> float: ...
    def can_run_on_mchn(self, mchn_id: str) -> bool: ...