from typing import NamedTuple, Generator
from enum import Enum
from swmtplanner.excel.engine import file

__all__ = ['TokType', 'Token', 'tokenize', 'Tokenized']

def tokenize(f: file.File) -> Generator[Token]: ...

class TokType(Enum):
    WS = ...
    RAW_INDENT = ...
    ELLIPSIS = ...
    COMMENT = ...
    NEWLINE = ...
    INDENT = ...
    DEDENT = ...
    LBRACK = ...
    RBRACK = ...
    LPAREN = ...
    RPAREN = ...
    COLON = ...
    COMMA = ...
    ARROW = ...
    DOT = ...
    EQ = ...
    STAR = ...
    SLASH = ...
    PCT = ...
    PLUS = ...
    MINUS = ...
    INT = ...
    FLOAT = ...
    STRING = ...
    NAME = ...
    TO = ...
    END = ...

class Token(NamedTuple):
    kind: TokType
    value: str
    start: file.Pos

class Tokenized:
    def __init__(self, file: file.File) -> None: ...
    @property
    def ended(self) -> bool: ...
    @property
    def last_tok(self) -> Token: ...
    def advance(self) -> Token: ...
    def backup(self, n: int) -> None: ...