from pathlib import Path

import pandas as pd

from .loop import PlanReport

__all__ = [
    'demand_dataframe',
    'schedule_dataframe', 'production_dataframe', 'xref_dataframe',
    'unmet_demand_dataframe',
    'late_orders_dataframe', 'write_plan_report_xlsx',
    'iteration_log_dataframe',
    'cost_detail_dataframe',
    'lateness_detail_dataframe', 'drainage_detail_dataframe',
    'carrying_detail_dataframe', 'excess_detail_dataframe',
    'priority_detail_dataframe',
    'schedule_detail_dataframe',
    'write_verbose_log_tsvs',
    'write_dashboard_html',
]


def demand_dataframe(report: PlanReport) -> pd.DataFrame: ...
def schedule_dataframe(report: PlanReport) -> pd.DataFrame: ...
def production_dataframe(report: PlanReport) -> pd.DataFrame: ...
def xref_dataframe(report: PlanReport) -> pd.DataFrame: ...
def late_orders_dataframe(report: PlanReport) -> pd.DataFrame: ...
def unmet_demand_dataframe(report: PlanReport) -> pd.DataFrame: ...
def iteration_log_dataframe(report: PlanReport) -> pd.DataFrame: ...
def cost_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def lateness_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def drainage_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def carrying_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def excess_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def priority_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def schedule_detail_dataframe(report: PlanReport) -> pd.DataFrame: ...
def write_plan_report_xlsx(
    report: PlanReport, path: str | Path,
) -> None: ...
def write_verbose_log_tsvs(
    report: PlanReport, dir_path: str | Path,
) -> None: ...
def write_dashboard_html(
    report: PlanReport, path: str | Path,
) -> None: ...
