from datetime import datetime
from typing import Protocol, Literal, Hashable, NamedTuple
from abc import abstractmethod

class HasID[T: Hashable](Protocol):
    """
    A simple protocol for defining objects uniquely identified
    by ids not provided by the system.
    """
    def __hash__(self) -> int: ...
    def __eq__(self, value: 'HasID[T]') -> bool: ...
    def __repr__(self) -> str: ...
    @property
    @abstractmethod
    def prefix(self) -> str:
        """Used to distinguish between different HasID implementations."""
        ...
    @property
    @abstractmethod
    def id(self) -> T:
        """The unique, hashable id of this object."""
        ...

_Beam = str # description of the beamset
_Bar = tuple[_Beam, float] # a beam and the pct consumed by weight

class Greige(HasID[str]):
    def __init__(self, name: str, family: str, beam_config: tuple[_Bar, _Bar],
                 tgt_wt: float, machines: dict[str, float]) -> None: ...
    @property
    def family(self) -> str:
        """The style family of this greige item."""
        ...
    @property
    def top_set(self) -> str:
        """The beamset used on the top bar to produce this greige item."""
        ...
    @property
    def btm_set(self) -> str:
        """The beamset used on the bottom bar to produce this greige item."""
        ...
    @property
    def top_pct(self) -> float:
        """The percent of the top beamset consumed by weight."""
        ...
    @property
    def btm_pct(self) -> float:
        """The percent of the bottom beamset consumed by weight."""
        ...
    @property
    def tgt_wt(self) -> float:
        """The target lbs/roll of greige fabric."""
        ...
    def can_run_on(self, mchn: str) -> bool:
        """Whether this greige style can be produced on the given machine."""
        ...
    def get_rate_on(self, mchn: str) -> float:
        """The rate of production on the given machine in lbs/hour."""
        ...

class BeamSet(HasID[int]):
    def __init__(self, name: str, init_lbs: float) -> None: ...
    @property
    def name(self) -> str:
        """A description of this beamset."""
        ...
    @property
    def denier(self) -> int: ...
    @property
    def lbs(self) -> float:
        """How many lbs remain on this beamset after the schedule has finished running."""
        ...
    def rem_lbs_by(self, date: datetime) -> float:
        """Returns the lbs remaining on this beamset by the given date."""
        ...
    def use(self, item: Greige, mchn: str, bar: Literal['top', 'btm'],
            start: datetime, end: datetime) -> None:
        """
        Log a usage of this beamset.

        Args:
          item: The Greige item being produced.
          mchn: The name of the machine the beamset is assigned to.
          bar: Which bar the beamset is on ('top' or 'btm').
          start: The start date/time of the job.
          end: The end date/time of the job.
        """
        ...

class Job(HasID[str]):
    def __init__(self, item: Greige, start: datetime, end: datetime,
                 lbs_used_top: float, lbs_used_btm: float, lbs_prod: float) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def req(self) -> Req: ...
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def lbs_used_top(self) -> float: ...
    @property
    def lbs_used_btm(self) -> float: ...
    @property
    def lbs_prod(self) -> float: ...

class InvTracker:
    def __init__(self, item: Greige, safety_lbs: float, safety_rolls: int,
                 init_lbs: float, init_rolls: int) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def safety_lbs(self) -> float: ...
    @property
    def safety_rolls(self) -> int: ...
    def create_order(self, date: datetime, rolls: int) -> Order: ...

class Production(NamedTuple):
    job: str
    start: datetime
    end: datetime
    rolls: int

class Req:
    def __init_subclass__(cls, read_only: tuple[str, ...] = ...,
                          priv: tuple[str, ...] = ...) -> None:
        ...
    def __init__(self, item: Greige, rolls: int, year: int, week: int, prty: int,
                 tracker: InvTracker, **kwargs) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def rolls(self) -> int: ...
    @property
    def lbs(self) -> float: ...
    @property
    def year(self) -> int: ...
    @property
    def week(self) -> int: ...
    @property
    def prty(self) -> int: ...
    @property
    def job(self) -> Job | None: ...
    def assign(self, job: Job) -> None: ...

class Order(Req):
    def __init__(self, item: Greige, rolls: int, date: datetime, tracker: InvTracker) -> None: ...
    @property
    def date(self) -> datetime: ...

class Safety(Req):
    def __init__(self, item: Greige, rolls: int, year: int, week: int, tracker: InvTracker) -> None: ...