from datetime import datetime, date
from typing import Literal, Hashable, Protocol, Sequence, Callable, TypeVar
from abc import abstractmethod

_TapeOut = tuple[Literal['top_to', 'btm_to', 'top_chg', 'btm_chg'], str, datetime]
_RunOut = tuple[Literal['top_ro', 'btm_ro'], datetime]

class HasID[T: Hashable](Protocol):
    """
    A simple protocol for defining objects uniquely identified
    by ids not provided by the system.
    """
    def __hash__(self) -> int: ...
    def __eq__(self, value: 'HasID[T]') -> bool: ...
    def __repr__(self) -> str: ...
    @property
    @abstractmethod
    def prefix(self) -> str:
        """Used to distinguish between different HasID implementations."""
        ...
    @property
    @abstractmethod
    def id(self) -> T:
        """The unique, hashable id of this object."""
        ...

class WorkCal:
    """
    A class for defining custom business calendars and performing datetime
    calculations with them.
    """
    def __init__(self, business_hrs: tuple[int, int], work_days: Sequence[int],
                 start: datetime, holidays: Sequence[date], cal_shift: float = ...) -> None:
        """
        Initialize a new WorkCal object.

          business_hrs:
            A 2-tuple representing the start and end of the business day as
            integers (0-24).
          work_days:
            A sequence of integers corresponding to the working days of the
            week where Monday=0.
          start:
            The date and time this working calendar starts.
          holidays:
            A sequence of dates corresponding to non-working holidays.
          cal_shift (default=0):
            For 24-hour days only. A float representing the number of hours to
            "shift" this calendar from standard day boundaries. For example,
            if the first shift of the day starts at 11pm, you should pass in -1
            here.
        """
        ...
    @property
    def wd_start(self) -> int:
        """The hour when the work day starts (0-24)."""
        ...
    @property
    def wd_end(self) -> int:
        """The hour when the work day ends (0-24)."""
        ...
    @property
    def work_days(self) -> tuple[int, ...]:
        """The business days as integers (Monday=0)."""
        ...
    def add_work_hrs(self, start: datetime, hrs: float) -> datetime:
        """
        Convert a duration in working hours to a real end datetime.

          start:
            The start datetime of the working interval.
          hrs:
            The number of working hours in the interval.
        
        Returns the end datetime of the provided working interval.
        """
        ...
    def get_work_hrs_between(self, start: datetime, end: datetime) -> float:
        """
        Calculate the available working hours between two datetimes.

          start:
            The start datetime.
          end:
            The end datetime.
        
        Returns the available working hours as a float.
        """
        ...
    
CT = TypeVar('CT')

class _Comparable(Protocol):
    def __lt__(self: CT, other: CT) -> bool: ...

class Queue[T, U: _Comparable]:
    def __init__(self, key_func: Callable[[T], U]) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def put(self, item: T) -> None: ...
    def get(self) -> T: ...
    def peek(self) -> T: ...

_Beam = str
_Bar = tuple[_Beam, float]

class Greige(HasID[str]):
    def __init__(self, name: str, family: str, beam_config: tuple[_Bar, _Bar],
                 tgt_wt: float, machines: dict[str, float]) -> None: ...
    @property
    def family(self) -> str: ...
    @property
    def top_set(self) -> str: ...
    @property
    def btm_set(self) -> str: ...
    @property
    def top_pct(self) -> float: ...
    @property
    def btm_pct(self) -> float: ...
    @property
    def tgt_wt(self) -> float: ...
    def can_run_on(self, mchn: str) -> bool: ...
    def get_rate_on(self, mchn: str) -> float: ...

class BeamSet(HasID[int]):
    def __init__(self, name: _Beam, init_lbs: float) -> None: ...
    @property
    def name(self) -> _Beam: ...
    @property
    def denier(self) -> int: ...
    @property
    def lbs(self) -> float: ...
    def rem_lbs_by(self, date: datetime) -> float: ...
    def use(self, lbs: float, by: datetime) -> None: ...

class Req:
    def __init_subclass__(cls, read_only: tuple[str, ...] = ...,
                          priv: tuple[str, ...] = ...) -> None:
        ...
    def __init__(self, item: Greige, rolls: int, week: int, prty: int,
                 tracker: InvTracker, **kwargs) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def rolls(self) -> int: ...
    @property
    def lbs(self) -> float: ...
    @property
    def week(self) -> int: ...
    @property
    def prty(self) -> int: ...
    @property
    def job(self) -> Job | None: ...
    def assign(self, job: Job) -> None: ...

class InvTracker:
    def __init__(self, item: Greige, safety_lbs: float, safety_rolls: int,
                 init_lbs: float, init_rolls: int) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def safety_lbs(self) -> float: ...
    @property
    def safety_rolls(self) -> int: ...
    def create_order(self, date: datetime, rolls: int) -> Order: ...
    def net_position_by(self, date: datetime) -> float: ...

class Order(Req):
    def __init__(self, item: Greige, rolls: int, date: datetime, tracker: InvTracker) -> None: ...
    @property
    def date(self) -> datetime: ...

class Safety(Req):
    def __init__(self, item: Greige, rolls: int, week: int, tracker: InvTracker) -> None: ...

type _RunOut = tuple[str, datetime]
type _Change = tuple[Literal['top_to', 'btm_to', 'top_chg', 'btm_chg'], str, datetime]

class Job(HasID[str]):
    def __init__(self, item: Greige, req: Req, start: datetime, end: datetime,
                 lbs_used_top: float, lbs_used_btm: float, lbs_prod: float,
                 changes: list[_Change], run_outs: list[_RunOut]) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def req(self) -> Req: ...
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def lbs_used_top(self) -> float: ...
    @property
    def lbs_used_btm(self) -> float: ...
    @property
    def lbs_prod(self) -> float: ...
    @property
    def changes(self) -> tuple[_Change, ...]: ...
    @property
    def run_outs(self) -> tuple[_RunOut, ...]: ...

class Machine(HasID[str]):
    def __init__(self, name: str, cal: WorkCal, item: Greige, top_rem: float,
                 btm_rem: float) -> None: ...
    @property
    def cal(self) -> WorkCal: ...
    @property
    def item(self) -> Greige: ...
    @property
    def top_set(self) -> BeamSet: ...
    @property
    def btm_set(self) -> BeamSet: ...
    @property
    def jobs(self) -> list[Job]: ...
    def next_runout(self) -> _RunOut: ...
    def next_decisions(self) -> list[tuple[str, datetime]]: ...
    def get_runouts(self, start: datetime, rolls: int, apply_changes: bool = False) \
        -> list[_RunOut]: ...
    def get_tapeouts(self, item: Greige) -> list[_TapeOut]:
        """
        Gets all the required beam changes and tape-outs needed to knit the
        given item next. Returns an empty list if no changes are needed. A
        tape out indicates the beam will be switched before running out.

          item:
            The next Greige item to knit.
        
        Returns a list of 3-tuples, where the first str indicates whether the
        change is a full tape out ('to') or a beam change after a run out
        ('chg') and whether it occurred on the top or bottom bar. The second
        str is a description of the new beamset product that will be loaded on,
        and the final element is the date/time the change will occur.
        """
        ...