from .dyecycle import DyeCycle, DyeCycleView

import datetime as dt
from swmtplanner.support import DateRange, FloatRange
from swmtplanner.swmttypes.products.fabric.color import Shade
from swmtplanner.swmttypes.schedule import Schedule
from swmtplanner.planners.parkave.materials import DyeLot

__all__ = ['DyeCycle', 'DyeCycleView']

class JetSched(Schedule, read_only=('jet','n_ports','jss','mss')):
    def __init__(self, jet_id: str, n_ports: int, date_rng: DateRange,
                 days_open: FloatRange = ...) -> None: ...
    @property
    def jobs(self) -> list[DyeCycleView]: ...
    @property
    def prod_jobs(self) -> list[DyeCycleView]: ...
    @property
    def jet(self) -> str: ...
    @property
    def n_ports(self) -> int: ...
    @property
    def jss(self) -> int: ...
    @property
    def mss(self) -> Shade: ...
    def can_add_lots(self, lots: list[DyeLot], _: dt.timedelta) -> bool: ...
    def add_lots(self, lots: list[DyeLot], _: dt.timedelta,
                 idx: int | None = None) -> list[DyeCycle]: ...
    def add_job(self, job: DyeCycle, force: bool = False) -> None: ...