import datetime as dt
from swmtplanner.swmttypes.products import GreigeStyle, fabric
from swmtplanner.swmttypes.schedule import Job, JobView
from swmtplanner.planners.parkave.materials import DyeLot, DyeLotView

__all__ = ['DyeCycle', 'DyeCycleView']

class DyeCycle(Job[GreigeStyle]):
    def __init__(self, lots: list[DyeLot], start: dt.datetime,
                 moveable: bool = True, idx: int = None) -> None: ...
    @property
    def color(self) -> fabric.Color: ...
    @property
    def shade(self) -> fabric.color.Shade: ...
    @property
    def lots(self) -> list[DyeLotView]: ...
    @property
    def min_date(self) -> dt.datetime: ...
    def copy_lots(self, start: dt.datetime, cycle_time: dt.timedelta,
                  moveable: bool, idx: int | None = None) -> DyeCycle: ...
    def view(self) -> DyeCycleView: ...

class DyeCycleView(JobView[GreigeStyle], attrs=('color','shade')):
    def __init__(self, link: DyeCycle) -> None: ...
    @property
    def color(self) -> fabric.Color: ...
    @property
    def shade(self) -> fabric.color.Shade: ...
    @property
    def lots(self) -> list[DyeLotView]: ...
    @property
    def min_date(self) -> dt.datetime: ...
    def copy_lots(self, start: dt.datetime, cycle_time: dt.timedelta,
                  moveable: bool, idx: int | None = None) -> DyeCycle: ...