from swmtplanner.swmttypes.product import Greige
from swmtplanner.swmttypes.schedule import Job

__all__ = ['Req']

class Req:
    def __init_subclass__(cls, read_only: tuple[str, ...] = ...,
                          priv: tuple[str, ...] = ...) -> None:
        ...
    def __init__(self, item: Greige, rolls: int, week: int, prty: int,
                 **kwargs) -> None: ...
    @property
    def item(self) -> Greige: ...
    @property
    def rolls(self) -> int: ...
    @property
    def lbs(self) -> float: ...
    @property
    def week(self) -> int: ...
    @property
    def prty(self) -> int: ...
    @property
    def job(self) -> Job | None: ...
    def assign(self, job: Job) -> None: ...