import pandas as pd
from . import parser, info

__all__ = ['parser', 'info']

def init() -> None: ...
def get_read_args(name: str) -> info.PandasInfo: ...
def load_df(info: str, default_dir: str) -> pd.DataFrame: ...
def to_tsv_file(name: str, default_dir: str, outpath: str) -> None: ...