from swmtplanner.support import SwmtBase

class Quantity(SwmtBase, read_only=('pcs','yds','lbs')):
    def __init__(self, pcs: float | None = None, yds: float | None = None,
                 lbs: float | None = None) -> None: ...
    def __eq__(self, value: 'Quantity') -> bool: ...
    def __le__(self, value: 'Quantity') -> bool: ...
    def __lt__(self, value: 'Quantity') -> bool: ...
    def __ge__(self, value: 'Quantity') -> bool: ...
    def __gt__(self, value: 'Quantity') -> bool: ...
    def __add__(self, value: 'Quantity') -> 'Quantity': ...
    def __sub__(self, value: 'Quantity') -> 'Quantity': ...
    def __mul__(self, scalar: float) -> 'Quantity': ...
    def __rmul__(self, scalar: float) -> 'Quantity': ...
    def __div__(self, scalar: float) -> 'Quantity': ...
    @property
    def pcs(self) -> float | None: ...
    @property
    def yds(self) -> float | None: ...
    @property
    def lbs(self) -> float | None: ...