from swmtplanner.support import HasID

_BeamSet = str
_Bar = tuple[_BeamSet, float]

__all__ = ['Greige']

class Greige(HasID[str]):
    def __init__(self, name: str, family: str, beam_config: tuple[_Bar, _Bar],
                 machines: dict[str, float]) -> None: ...
    @property
    def family(self) -> str: ...
    @property
    def top_set(self) -> str: ...
    @property
    def btm_set(self) -> str: ...
    @property
    def top_pct(self) -> float: ...
    @property
    def btm_pct(self) -> float: ...
    def can_run_on(self, mchn: str) -> bool: ...
    def get_rate_on(self, mchn: str) -> float: ...