from datetime import datetime
from swmtplanner.support import HasID

_Beam = str
_Bar = tuple[_Beam, float]

__all__ = ['Greige', 'BeamSet']

class Greige(HasID[str]):
    def __init__(self, name: str, family: str, beam_config: tuple[_Bar, _Bar],
                 tgt_wt: float, machines: dict[str, float]) -> None: ...
    @property
    def family(self) -> str: ...
    @property
    def top_set(self) -> str: ...
    @property
    def btm_set(self) -> str: ...
    @property
    def top_pct(self) -> float: ...
    @property
    def btm_pct(self) -> float: ...
    @property
    def tgt_wt(self) -> float: ...
    def can_run_on(self, mchn: str) -> bool: ...
    def get_rate_on(self, mchn: str) -> float: ...

class BeamSet(HasID[int]):
    def __init__(self, name: str, init_lbs: float) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def denier(self) -> int: ...
    @property
    def lbs(self) -> float: ...
    def rem_lbs_by(self, date: datetime) -> float: ...
    def use(self, lbs: float, by: datetime) -> None: ...